### PR TITLE
explicitly depend on cl-ppcre

### PR DESCRIPTION
**Pull request by PuercoPop**

### CODE REVIEW

**Comment by diogofsr** [comment]
I didn't add cl-ppcre as a dependency because StumpWM already depends on it and pavol depends on StumpWM; but you are right, pavol should explicitly depend on cl-ppcre.

About the asdf-user, I see it on the ASDF manual example.  It talks about ASDF 3.  Do you know if it will keep working with earlier versions of ASDF?

**Comment by diogofsr** [comment]
Ah, thank you for the patch!

**Comment by PuercoPop** [comment]
Hi, you are right, asdf-user requires asdf3. So it wouldn't work on CLISP. I tend to err on the side of "whatever works on SBCL". The important thing is to depend explicitly on cl-ppcre.

Thanks for pavol!

**Comment by diogofsr** [comment]
> Hi, you are right, asdf-user requires asdf3. So it wouldn't work on
> CLISP. I tend to err on the side of "whatever works on SBCL". The
> important thing is to depend explicitly on cl-ppcre.

:-)

Oh, then I will revert the :asdf-user part.

> Thanks for pavol!

You are welcome!

**Pull request merged**
